title: My Projects Portfolio
description: Akshay Bhosale (Master's Student in Computer Engineering)
             University of Delaware
Imagefile: images/my_image.jpg
theme: jekyll-theme-cayman
email: akshay@udel.edu
